### ISSUE TITLE
Failing with exception in Scala 2.10.2

### ISSUE THREAD

**Issue by rgladwell** [mariusae/mustache.scala#2]
I get a exception when attempting to call the Mustache constructor:

Exception:
java.lang.NoSuchMethodError
org.monkey.mustache.Dictionary$.apply(Dictionary.scala:16) me.gladwell.peachtree.MustachePageModule$class.me$gladwell$peachtree$MustachePageModule$$parseMustacheTemplate(MustachePageModule.scala:38) me.gladwell.peachtree.MustachePageModule$MustachePageLoader.load(MustachePageModule.scala:58) me.gladwell.peachtree.MustachePageLoaderSpec$$anonfun$1.apply$mcV$sp(MustachePageLoaderSpec.scala:23) me.gladwell.peachtree.MustachePageLoaderSpec$$anonfun$1.apply(MustachePageLoaderSpec.scala:21) me.gladwell.peachtree.MustachePageLoaderSpec$$anonfun$1.apply(MustachePageLoaderSpec.scala:21) org.scalatest.FlatSpec$$anon$1.apply(FlatSpec.scala:2977) org.scalatest.Suite$class.withFixture(Suite.scala:1974) me.gladwell.peachtree.MustachePageLoaderSpec.withFixture(MustachePageLoaderSpec.scala:8) org.scalatest.FlatSpec$class.invokeWithFixture$1(FlatSpec.scala:2974) org.scalatest.FlatSpec$$anonfun$runTest$1.apply(FlatSpec.scala:2983) org.scalatest.FlatSpec$$anonfun$runTest$1.apply(FlatSpec.scala:2983) org.scalatest.SuperEngine.runTestImpl(Engine.scala:198) org.scalatest.FlatSpec$class.runTest(FlatSpec.scala:2983) me.gladwell.peachtree.MustachePageLoaderSpec.runTest(MustachePageLoaderSpec.scala:8) org.scalatest.FlatSpec$$anonfun$runTests$1.apply(FlatSpec.scala:3045) org.scalatest.FlatSpec$$anonfun$runTests$1.apply(FlatSpec.scala:3045) org.scalatest.SuperEngine$$anonfun$org$scalatest$SuperEngine$$runTestsInBranch$1.apply(Engine.scala:260) org.scalatest.SuperEngine$$anonfun$org$scalatest$SuperEngine$$runTestsInBranch$1.apply(Engine.scala:249) scala.collection.immutable.List.foreach(List.scala:318) org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:249) org.scalatest.SuperEngine.runTestsImpl(Engine.scala:326) org.scalatest.FlatSpec$class.runTests(FlatSpec.scala:3045) me.gladwell.peachtree.MustachePageLoaderSpec.runTests(MustachePageLoaderSpec.scala:8) org.scalatest.Suite$class.run(Suite.scala:2303) me.gladwell.peachtree.MustachePageLoaderSpec.org$scalatest$FlatSpec$$super$run(MustachePageLoaderSpec.scala:8) org.scalatest.FlatSpec$$anonfun$run$1.apply(FlatSpec.scala:3092) org.scalatest.FlatSpec$$anonfun$run$1.apply(FlatSpec.scala:3092) org.scalatest.SuperEngine.runImpl(Engine.scala:362) org.scalatest.FlatSpec$class.run(FlatSpec.scala:3092) me.gladwell.peachtree.MustachePageLoaderSpec.run(MustachePageLoaderSpec.scala:8) org.scalatest.Suite$class.callExecuteOnSuite$1(Suite.scala:2403) org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:2433) org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:2431) scala.collection.immutable.Range.foreach(Range.scala:141) org.scalatest.Suite$class.runNestedSuites(Suite.scala:2431) org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:28) org.scalatest.Suite$class.run(Suite.scala:2300) org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:28) org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:60) org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:1604) org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:1601) scala.collection.immutable.List.foreach(List.scala:318) org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1601) org.scalatest.tools.RunnerJFrame$RunnerThread$$anonfun$run$1.apply(RunnerJFrame.scala:1361) org.scalatest.tools.RunnerJFrame$RunnerThread$$anonfun$run$1.apply(RunnerJFrame.scala:1359) org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1645) org.scalatest.tools.RunnerJFrame$RunnerThread.run(RunnerJFrame.scala:1358)

**Comment by rgladwell** [comment]
java.lang.NoSuchMethodError: scala.collection.immutable.Map$.apply(Lscala/collection/Seq;)Lscala/collection/Map;
  at org.monkey.mustache.Dictionary$.apply(Dictionary.scala:16)
  at me.gladwell.peachtree.MustachePageModule$class.me$gladwell$peachtree$MustachePageModule$$parseMustacheTemplate(MustachePageModule.scala:38)
  at me.gladwell.peachtree.MustachePageModule$MustachePageLoader.load(MustachePageModule.scala:58)
  at me.gladwell.peachtree.MustachePageLoaderSpec$$anonfun$1.apply$mcV$sp(MustachePageLoaderSpec.scala:23)
  at me.gladwell.peachtree.MustachePageLoaderSpec$$anonfun$1.apply(MustachePageLoaderSpec.scala:21)
  at me.gladwell.peachtree.MustachePageLoaderSpec$$anonfun$1.apply(MustachePageLoaderSpec.scala:21)
  at org.scalatest.FlatSpec$$anon$1.apply(FlatSpec.scala:2977)
  at org.scalatest.Suite$class.withFixture(Suite.scala:1974)
  at me.gladwell.peachtree.MustachePageLoaderSpec.withFixture(MustachePageLoaderSpec.scala:8)
  at org.scalatest.FlatSpec$class.invokeWithFixture$1(FlatSpec.scala:2974)

**Comment by rgladwell** [comment]
Any update on this?

**Comment by mariusae** [comment]
This sounds like a scala version mismatch. mustache.scala will have to be recompiled for scala 2.10.x

**Comment by rgladwell** [comment]
It might be worth deploying cross-compiled versions of this library to your repository:

http://www.scala-sbt.org/0.12.2/docs/Detailed-Topics/Cross-Build.html
